HOST: http://myretail.avantcore.cz:14500/

--- myRetail ---

--
Autentication
The following is a section of resources related to autentication (login, logout, register)
--

Simple login by username and password
POST /login
{"username": "misak113", "password": "testheslo"}
< 200
< Content-Type: application/json
{ "status": "loggedIn", "message": "Uživatel přihlášen", "time": 135489548, "data": {
    "accessToken": "77d450bbbd948bb44cfa68a21a6c84be0b0a48ea953d2b4214a7d4a74c06ed7c",
    "user_oid": "512e6a85dea8ace96a5855b5",
}}

Logout user
POST /logout
{"username": "misak113", "accessToken": "77d450bbbd948bb44cfa68a21a6c84be0b0a48ea953d2b4214a7d4a74c06ed7c"}
< 200
< Content-Type: application/json
{ "status": "loggedOff", "message": "Uživatel odhlášen", "time": 135489548, "data": {}}

Simple register user
POST /register
{"username": "misak113", "password": "mojeheslo"}
< 200
< Content-Type: application/json
{ "status": "registered", "message": "Uživatel zaregistrován", "time": 135489548, "data": {}}


--
Getting Data
The following is a section of resources related to getting data from server
--


Get list of offers for specified user, if has permission
GET /offers
> Content-Type: application/json
{ "user_oid": "512e6a85dea8ace96a5855b5"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Nabídky vráceny", "data": {
    "offers": [
        {
        	"_id" : {"$oid": "512e6a7bdea8ace96a5855b4"},
			"title" : "Lahodná rajčátka",
			"description" : "Nepřehlédněte nabídku čtvrt kila lahodných rajčat první jakosti",
			"price" : 18.54,
			"currency" : "czk",
			"date_start" : "2013-01-02T12:00:00",
			"date_end" : "2013-01-18T18:59:59",
            "qtyLimitTotal" : 100,
            "qtyLimitUser" : 10,
            "categories": ["personal", "common"],
			"product" : {
				"id" : 146860,
				"name" : "Rajčata",
				"title" : "Rajčata Balení 250g",
				"product_code" : "566489138",
				"short_description" : "",
				"description" : null,
				"quantity" : 250,
				"measure_unit" : "g",
				"price" : 25.8,
				"currency" : "czk",
				"image": {
                    "small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
                    "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                    "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                },
                "images" : [
						{
							"small" : "http://api.myretail.cz/images/tomate-250g-14860-1_small.png",
							"medium" : "http://api.myretail.cz/images/tomate-250g-14860-1_medium.png",
							"large" : "http://api.myretail.cz/images/tomate-250g-14860-1_large.png"
						},
						{
							"small" : "http://api.myretail.cz/images/tomate-250g-14860-2_small.png",
							"medium" : "http://api.myretail.cz/images/tomate-250g-14860-2_medium.png",
							"large" : "http://api.myretail.cz/images/tomate-250g-14860-2_large.png"
						} ]
			},
			"priority" : 0.890415,
			"image": {
				"small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
				"medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
				"large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
			},
			"images" : [ {
				"small" : "http://api.myretail.cz/images/super_tomate-250g-14860-1_small.png",
				"medium" : "http://api.myretail.cz/images/super_tomate-250g-14860-1_medium.png",
				"large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
			} ]
		},
		{
			"_id" : {"$oid": "512e6a85dea8ace96a5855b5"},
    		"title" : "Bílá čokoláda",
			"description" : "Čokoláda co se rozplývá na jazyku!",
			"price" : 42.89,
			"currency" : "czk",
			"date_start" : "2012-11-12T12:00:00",
			"date_end" : "2013-02-09T18:59:59",
            "qtyLimitTotal" : null,
            "qtyLimitUser" : 100,
            "categories": ["common"],
			"product" : {
				"id" : 146861,
				"name" : "Čokoláda",
				"title" : "Bílá čokoláda 120g",
				"product_code" : "566489148",
				"short_description" : "",
				"description" : null,
				"quantity" : 120,
				"measure_unit" : "g",
				"price" : 75.9,
				"currency" : "czk",
				"image": {
                    "small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
                    "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                    "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                },
                "images" : [ {
					"small" : "http://api.myretail.cz/images/chocolate-14861-1_small.png",
					"medium" : "http://api.myretail.cz/images/chocolate-14861-1_medium.png",
					"large" : "http://api.myretail.cz/images/chocolate-14861-1_large.png"
				} ]
			},
			"priority" : 0.451437,
			"image": {
				"small" : "http://yojoyfrozenyogurt.com/wp-content/uploads/catablog/thumbnails/white%20chocolate%20mousse.jpg",
				"medium" : "http://www.friarsofkeswick.co.uk/files/imagecache/product_list/files/white_marzipan2_0.jpg",
				"large" : "http://api.myretail.cz/images/chocolate-14861-1_large.png"
			},
			"images" : []
		}
    ]
}}





Get one offer for specified user by offer id, if has permission
GET /offer
> Content-Type: application/json
{ "offer_oid": "512e6a7bdea8ace96a5855b4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Nabídka vrácena", "data": {
    "offer": {
    	"_id" : {"$oid": "512e6a7bdea8ace96a5855b4"},
		"title" : "Lahodná rajčátka",
		"description" : "Nepřehlédněte nabídku čtvrt kila lahodných rajčat první jakosti",
		"price" : 18.54,
		"currency" : "czk",
		"date_start" : "2013-01-02T12:00:00",
		"date_end" : "2013-01-18T18:59:59",
        "qtyLimitTotal" : 100,
        "qtyLimitUser" : 10,
        "categories": ["personal", "common"],
		"product" : {
			"id" : 146860,
			"name" : "Rajčata",
			"title" : "Rajčata Balení 250g",
			"product_code" : "566489138",
			"short_description" : "",
			"description" : null,
			"quantity" : 250,
			"measure_unit" : "g",
			"price" : 25.8,
			"currency" : "czk",
			"image": {
                "small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
                "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
            },
            "images" : [
					{
						"small" : "http://api.myretail.cz/images/tomate-250g-14860-1_small.png",
						"medium" : "http://api.myretail.cz/images/tomate-250g-14860-1_medium.png",
						"large" : "http://api.myretail.cz/images/tomate-250g-14860-1_large.png"
					},
					{
						"small" : "http://api.myretail.cz/images/tomate-250g-14860-2_small.png",
						"medium" : "http://api.myretail.cz/images/tomate-250g-14860-2_medium.png",
						"large" : "http://api.myretail.cz/images/tomate-250g-14860-2_large.png"
					} ]
		},
		"priority" : 0.890415,
		"image": {
			"small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
			"medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
			"large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
		},
		"images" : [ {
			"small" : "http://api.myretail.cz/images/super_tomate-250g-14860-1_small.png",
			"medium" : "http://api.myretail.cz/images/super_tomate-250g-14860-1_medium.png",
			"large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
		} ]
	}
}}




Get list of purchases for specified user, if has permission
GET /purchases
> Content-Type: application/json
{ "user_oid": "512e6a7bdea8ace96a5855b4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Nákupy vráceny", "data": {
    "purchases": [
        {
        	"_id" : {"$oid": "512e6a7bdea8ace96a5855c4"},
    		"date": "2013-01-02T12:00:00",
    		"totalPrice": 152.60,
    		"originalPrice": 195.12,
    		"currency": 'czk',
    		"loyaltyPoints": 12,
    		"paymentType": {
    			"name": 'visa',
    			"title": 'Visa card'
    		},
    		"branch": {
    			"name": 'Interspar Zličín',
    			"geolocation": {
    				"lat": 50.0725058,
    				"lon": 14.5421189
    			},
    			"phones": [
    				'+420 234 672 111',
    				'+420 234 670 119'
    			],
    			"address": {
    				"street": 'Nákupní 1/388',
    				"postcode": '102 00',
    				"city": 'Praha 10, Praha-Štěrboholy'
    			}
    		},
    		"items": [
    			{
    				"_id" : {"$oid": "512e6a7bdea8ace96a5855d5"},
    				"qty": 3,
    				"price": 22.97,
    				"currency": 'czk',
    				"offer": {
    					"_id" : {"$oid": "512e6a7bdea8ace96a5855e4"},
    					"title" : "Lahodná rajčátka",
    					"description" : "Nepřehlédněte nabídku čtvrt kila lahodných rajčat první jakosti",
    					"price" : 18.54,
    					"currency" : "czk",
    					"date_start" : "2013-01-02T12:00:00",
    					"date_end" : "2013-01-18T18:59:59",
    	                "qtyLimit" : 100,
    					"product" : {
    						"_id" : {"$oid": "512e6a7bdea8ace96a5855f4"},
    						"name" : "Rajčata",
    						"title" : "Rajčata Balení 250g",
    						"product_code" : "566489138",
    						"short_description" : "",
    						"description" : null,
    						"quantity" : 250,
    						"measure_unit" : "g",
    						"price" : 25.8,
    						"currency" : "czk",
    						"image": {
    							"small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
    							"medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
    							"large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
    						},
    						"images" : [
    								{
    									"small" : "http://api.myretail.cz/images/tomate-250g-14860-1_small.png",
    									"medium" : "http://api.myretail.cz/images/tomate-250g-14860-1_medium.png",
    									"large" : "http://api.myretail.cz/images/tomate-250g-14860-1_large.png"
    								},
    								{
    									"small" : "http://api.myretail.cz/images/tomate-250g-14860-2_small.png",
    									"medium" : "http://api.myretail.cz/images/tomate-250g-14860-2_medium.png",
    									"large" : "http://api.myretail.cz/images/tomate-250g-14860-2_large.png"
    								} ]
    					},
    					"priority" : 0.890415,
    					"image": {
    						"small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
    						"medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
    						"large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
    					},
    					"images" : [ {
    						"small" : "http://api.myretail.cz/images/super_tomate-250g-14860-1_small.png",
    						"medium" : "http://api.myretail.cz/images/super_tomate-250g-14860-1_medium.png",
    						"large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
    					} ]
    				},
    				"product" : {
        					"_id" : {"$oid": "512e6a7bdea8ace96a5855f5"},
        					"name" : "Rajčátka",
        					"title" : "Bílá čokoláda 120g",
        					"product_code" : "566489148",
        					"short_description" : "",
        					"description" : null,
        					"quantity" : 120,
        					"measure_unit" : "g",
        					"price" : 165.9,
        					"currency" : "czk",
        					"image": {
    							"small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
    							"medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
    							"large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
    						},
    						"images" : [ {
        						"small" : "http://api.myretail.cz/images/chocolate-14861-1_small.png",
        						"medium" : "http://api.myretail.cz/images/chocolate-14861-1_medium.png",
        						"large" : "http://api.myretail.cz/images/chocolate-14861-1_large.png"
        					} ]
        				}
    			},
    			{
    				"_id" : {"$oid": "512e6a7bdea8ace96a5855d6"},
    				"qty": 3,
    				"price": 12.97,
    				"currency": 'czk',
    				"offer": null,
    				"product" : {
        					"_id" : {"$oid": "512e6a7bdea8ace96a5855e7"},
        					"name" : "Čokoláda",
        					"title" : "Bílá čokoláda 120g",
        					"product_code" : "566489148",
        					"short_description" : "",
        					"description" : null,
        					"quantity" : 120,
        					"measure_unit" : "g",
        					"price" : 165.9,
        					"currency" : "czk",
        					"image": {
    							"small" : "http://yojoyfrozenyogurt.com/wp-content/uploads/catablog/thumbnails/white%20chocolate%20mousse.jpg",
    							"medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
    							"large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
    						},
    						"images" : [ {
        						"small" : "http://api.myretail.cz/images/chocolate-14861-1_small.png",
        						"medium" : "http://api.myretail.cz/images/chocolate-14861-1_medium.png",
        						"large" : "http://api.myretail.cz/images/chocolate-14861-1_large.png"
        					} ]
        				}
    			},
    			{
    				"_id" : {"$oid": "512e6a7bdea8ace96a5854f4"},
    				"qty": 1,
    				"price": -45.21,
    				"currency": 'czk',
    				"offer": null,
    				"product": null
    			}
    		]
    	},
    	{
    		"_id" : {"$oid": "512e6a7bdea8ace96a5855c5"},
    		"date": "2013-01-15T12:00:00",
    		"totalPrice": 292.60,
    		"originalPrice": 295.12,
    		"currency": 'czk',
    		"loyaltyPoints": 5,
    		"paymentType": {
    			"name": 'cash',
    			"title": 'hotovost'
    		},
    		"branch": {
    			"name": 'Interspar Černý most',
    			"geolocation": {
    				"lat": 50.0725058,
    				"lon": 14.5421189
    			},
    			"phones": [
    				'+420 234 672 111',
    				'+420 234 670 119'
    			],
    			"address": {
    				"street": 'Nákupní 1/388',
    				"postcode": '102 00',
    				"city": 'Praha 10, Praha-Štěrboholy'
    			}
    		},
    		"items": [
    			{
    				"_id" : {"$oid": "512e6a7bdea8ace96a585c54"},
    				"qty": 3,
    				"price": 12.97,
    				"currency": 'czk',
    				"offer": null,
    				"product" : {
        					"_id" : {"$oid": "512e6a7bdea8ace96a5855d4"},
        					"name" : "Čokoláda",
        					"title" : "Bílá čokoláda 120g",
        					"product_code" : "566489148",
        					"short_description" : "",
        					"description" : null,
        					"quantity" : 120,
        					"measure_unit" : "g",
        					"price" : 165.9,
        					"currency" : "czk",
        					"image": {
    							"small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
    							"medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
    							"large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
    						},
    						"images" : [ {
        						"small" : "http://api.myretail.cz/images/chocolate-14861-1_small.png",
        						"medium" : "http://api.myretail.cz/images/chocolate-14861-1_medium.png",
        						"large" : "http://api.myretail.cz/images/chocolate-14861-1_large.png"
        					} ]
        				}
    			}
    		]
    	}
    ]
}}






Get one purchase for specified user by purchase id, if has permission
GET /purchase
> Content-Type: application/json
{ "purchase_oid": "512e6a7bdea8ace96a5855c4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Nákup vrácen", "data": {
    "purchase": {
        "_id" : {"$oid": "512e6a7bdea8ace96a5855c4"},
        "date": "2013-01-02T12:00:00",
        "totalPrice": 152.60,
        "originalPrice": 195.12,
        "currency": 'czk',
        "loyaltyPoints": 12,
        "paymentType": {
            "name": 'visa',
            "title": 'Visa card'
        },
        "branch": {
            "name": 'Interspar Zličín',
            "geolocation": {
                "lat": 50.0725058,
                "lon": 14.5421189
            },
            "phones": [
                '+420 234 672 111',
                '+420 234 670 119'
            ],
            "address": {
                "street": 'Nákupní 1/388',
                "postcode": '102 00',
                "city": 'Praha 10, Praha-Štěrboholy'
            }
        },
        "items": [
            {
                "_id" : {"$oid": "512e6a7bdea8ace96a5855d5"},
                "qty": 3,
                "price": 22.97,
                "currency": 'czk',
                "offer": {
                    "_id" : {"$oid": "512e6a7bdea8ace96a5855e4"},
                    "title" : "Lahodná rajčátka",
                    "description" : "Nepřehlédněte nabídku čtvrt kila lahodných rajčat první jakosti",
                    "price" : 18.54,
                    "currency" : "czk",
                    "date_start" : "2013-01-02T12:00:00",
                    "date_end" : "2013-01-18T18:59:59",
                    "qtyLimit" : 100,
                    "product" : {
                        "_id" : {"$oid": "512e6a7bdea8ace96a5855f4"},
                        "name" : "Rajčata",
                        "title" : "Rajčata Balení 250g",
                        "product_code" : "566489138",
                        "short_description" : "",
                        "description" : null,
                        "quantity" : 250,
                        "measure_unit" : "g",
                        "price" : 25.8,
                        "currency" : "czk",
                        "image": {
                            "small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
                            "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                            "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                        },
                        "images" : [
                                {
                                    "small" : "http://api.myretail.cz/images/tomate-250g-14860-1_small.png",
                                    "medium" : "http://api.myretail.cz/images/tomate-250g-14860-1_medium.png",
                                    "large" : "http://api.myretail.cz/images/tomate-250g-14860-1_large.png"
                                },
                                {
                                    "small" : "http://api.myretail.cz/images/tomate-250g-14860-2_small.png",
                                    "medium" : "http://api.myretail.cz/images/tomate-250g-14860-2_medium.png",
                                    "large" : "http://api.myretail.cz/images/tomate-250g-14860-2_large.png"
                                } ]
                    },
                    "priority" : 0.890415,
                    "image": {
                        "small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
                        "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                        "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                    },
                    "images" : [ {
                        "small" : "http://api.myretail.cz/images/super_tomate-250g-14860-1_small.png",
                        "medium" : "http://api.myretail.cz/images/super_tomate-250g-14860-1_medium.png",
                        "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                    } ]
                },
                "product" : {
                        "_id" : {"$oid": "512e6a7bdea8ace96a5855f5"},
                        "name" : "Rajčátka",
                        "title" : "Bílá čokoláda 120g",
                        "product_code" : "566489148",
                        "short_description" : "",
                        "description" : null,
                        "quantity" : 120,
                        "measure_unit" : "g",
                        "price" : 165.9,
                        "currency" : "czk",
                        "image": {
                            "small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
                            "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                            "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                        },
                        "images" : [ {
                            "small" : "http://api.myretail.cz/images/chocolate-14861-1_small.png",
                            "medium" : "http://api.myretail.cz/images/chocolate-14861-1_medium.png",
                            "large" : "http://api.myretail.cz/images/chocolate-14861-1_large.png"
                        } ]
                    }
            },
            {
                "_id" : {"$oid": "512e6a7bdea8ace96a5855d6"},
                "qty": 3,
                "price": 12.97,
                "currency": 'czk',
                "offer": null,
                "product" : {
                        "_id" : {"$oid": "512e6a7bdea8ace96a5855e7"},
                        "name" : "Čokoláda",
                        "title" : "Bílá čokoláda 120g",
                        "product_code" : "566489148",
                        "short_description" : "",
                        "description" : null,
                        "quantity" : 120,
                        "measure_unit" : "g",
                        "price" : 165.9,
                        "currency" : "czk",
                        "image": {
                            "small" : "http://yojoyfrozenyogurt.com/wp-content/uploads/catablog/thumbnails/white%20chocolate%20mousse.jpg",
                            "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                            "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                        },
                        "images" : [ {
                            "small" : "http://api.myretail.cz/images/chocolate-14861-1_small.png",
                            "medium" : "http://api.myretail.cz/images/chocolate-14861-1_medium.png",
                            "large" : "http://api.myretail.cz/images/chocolate-14861-1_large.png"
                        } ]
                    }
            },
            {
                "_id" : {"$oid": "512e6a7bdea8ace96a5854f4"},
                "qty": 1,
                "price": -45.21,
                "currency": 'czk',
                "offer": null,
                "product": null
            }
        ]
    }
}}





Get list of products by parametrs, if has permission
GET /products
> Content-Type: application/json
{ "category_oid": "512e6a7bdea8ace96a5854c4", tags: ["vegetable", "milk"]}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Produkty vráceny", "data": {
        "products": [
            {
                "_id" : {"$oid": "512e6a7bdea8ace96a5855f4"},
                "name" : "Rajčata",
                "title" : "Rajčata Balení 250g",
                "product_code" : "566489138",
                "short_description" : "",
                "description" : null,
                "quantity" : 250,
                "measure_unit" : "g",
                "price" : 25.8,
                "currency" : "czk",
                "category": {
                    "_id": {"$oid":"512e6a7bdea8ace96a5854c4"} 
                },
                "tags": ["tomate", "vegetable", "red"],
                "image": {
                    "small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
                    "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                    "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                },
                "images" : [
                        {
                            "small" : "http://api.myretail.cz/images/tomate-250g-14860-1_small.png",
                            "medium" : "http://api.myretail.cz/images/tomate-250g-14860-1_medium.png",
                            "large" : "http://api.myretail.cz/images/tomate-250g-14860-1_large.png"
                        },
                        {
                            "small" : "http://api.myretail.cz/images/tomate-250g-14860-2_small.png",
                            "medium" : "http://api.myretail.cz/images/tomate-250g-14860-2_medium.png",
                            "large" : "http://api.myretail.cz/images/tomate-250g-14860-2_large.png"
                        } ]
            },
            {
                "_id" : {"$oid": "512e6a7bdea8ace96a5855e7"},
                "name" : "Čokoláda",
                "title" : "Bílá čokoláda 120g",
                "product_code" : "566489148",
                "short_description" : "",
                "description" : null,
                "quantity" : 120,
                "measure_unit" : "g",
                "price" : 165.9,
                "currency" : "czk",
                "category": {
                    "_id": {"$oid":"512e6a7bdea8ace96a5854c4"} 
                },
                "tags": ["chocolate", "milk", "milka"],
                "image": {
                    "small" : "http://yojoyfrozenyogurt.com/wp-content/uploads/catablog/thumbnails/white%20chocolate%20mousse.jpg",
                    "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                    "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                },
                "images" : [ {
                    "small" : "http://api.myretail.cz/images/chocolate-14861-1_small.png",
                    "medium" : "http://api.myretail.cz/images/chocolate-14861-1_medium.png",
                    "large" : "http://api.myretail.cz/images/chocolate-14861-1_large.png"
                } ]
            }
        ]
    }
}



Get one product by id, if has permission
GET /product
> Content-Type: application/json
{ "product_oid": "512e6a7bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Produkt vrácen", "data": {
        "product": {
            "_id" : {"$oid": "512e6a7bdea8ace96a5855f4"},
            "name" : "Rajčata",
            "title" : "Rajčata Balení 250g",
            "product_code" : "566489138",
            "short_description" : "",
            "description" : null,
            "quantity" : 250,
            "measure_unit" : "g",
            "price" : 25.8,
            "currency" : "czk",
            "category": {
                "_id": {"$oid":"512e6a7bdea8ace96a5854c4"} 
            },
            "tags": ["tomate", "vegetable", "red"],
            "image": {
                "small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
                "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
            },
            "images" : [
                    {
                        "small" : "http://api.myretail.cz/images/tomate-250g-14860-1_small.png",
                        "medium" : "http://api.myretail.cz/images/tomate-250g-14860-1_medium.png",
                        "large" : "http://api.myretail.cz/images/tomate-250g-14860-1_large.png"
                    },
                    {
                        "small" : "http://api.myretail.cz/images/tomate-250g-14860-2_small.png",
                        "medium" : "http://api.myretail.cz/images/tomate-250g-14860-2_medium.png",
                        "large" : "http://api.myretail.cz/images/tomate-250g-14860-2_large.png"
                    } ]
        }
    }
}



Get user by id, if has permission
GET /user
> Content-Type: application/json
{ "user_oid": "512e6a7bdea8ace9135855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Uživatel vrácen", "data": {
        "user": {
            "_id" : {"$oid": "512e6a7bdea8ace96a5855f4"},
            "forename": "Michael",
            "surname": "Žabka",
            "email": "zabka.michael@seznam.cz",
            "authenticates": [
                {
                    "type": "username",
                    "identity": "misak113",
                    "verification": null,
                }
            ]
        }
    }
}



Get shopping-carts by user id, if has permission
GET /shopping-carts
> Content-Type: application/json
{ "user_oid": "512e6a7bdea8ace9135855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Nákupní seznamy vráceny", "data": {
        "shopping-carts": ["512e6a7bdea8ace96a5855f4","512e6a8bdea8ace96a5855f4","512e6a9bdea8ace96a5855f4"]
    }
}



Get shopping-cart by id, if has permission
GET /shopping-cart
> Content-Type: application/json
{ "shoping-list_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Nákupní seznam vrácen", "data": {
        "shopping-cart": {
            "_id" : {"$oid": "512e6a7bdea8ace06a5855c4"},
            "date": "2013-01-02T12:00:00",
            "totalPrice": 152.60,
            "originalPrice": 195.12,
            "currency": 'czk',
            "loyaltyPoints": 12,
            "items": [
                {
                    "_id" : {"$oid": "512e6a7bdea8ace96a5855d6"},
                    "type": "title",
                    "qty": 3,
                    "name": "Vajíčka"
                },
                {
                    "_id" : {"$oid": "512e6a7bdea8ace96a5855d6"},
                    "type": "product",
                    "qty": 3,
                    "price": 12.97,
                    "currency": 'czk',
                    "product" : {
                            "_id" : {"$oid": "512e6a7bdea8ace96a5855e7"},
                            "name" : "Čokoláda",
                            "title" : "Bílá čokoláda 120g",
                            "product_code" : "566489148",
                            "short_description" : "",
                            "description" : null,
                            "quantity" : 120,
                            "measure_unit" : "g",
                            "price" : 165.9,
                            "currency" : "czk",
                            "image": {
                                "small" : "http://yojoyfrozenyogurt.com/wp-content/uploads/catablog/thumbnails/white%20chocolate%20mousse.jpg",
                                "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                                "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                            },
                            "images" : [ {
                                "small" : "http://api.myretail.cz/images/chocolate-14861-1_small.png",
                                "medium" : "http://api.myretail.cz/images/chocolate-14861-1_medium.png",
                                "large" : "http://api.myretail.cz/images/chocolate-14861-1_large.png"
                            } ]
                        }
                },
                {
                    "_id" : {"$oid": "512e6a7bdea8ace96a5855d5"},
                    "type": "offer",
                    "qty": 3,
                    "price": 22.97,
                    "currency": 'czk',
                    "offer": {
                        "_id" : {"$oid": "512e6a7bdea8ace96a5855e4"},
                        "title" : "Lahodná rajčátka",
                        "description" : "Nepřehlédněte nabídku čtvrt kila lahodných rajčat první jakosti",
                        "price" : 18.54,
                        "currency" : "czk",
                        "date_start" : "2013-01-02T12:00:00",
                        "date_end" : "2013-01-18T18:59:59",
                        "qtyLimit" : 100,
                        "product" : {
                            "_id" : {"$oid": "512e6a7bdea8ace96a5855f4"},
                            "name" : "Rajčata",
                            "title" : "Rajčata Balení 250g",
                            "product_code" : "566489138",
                            "short_description" : "",
                            "description" : null,
                            "quantity" : 250,
                            "measure_unit" : "g",
                            "price" : 25.8,
                            "currency" : "czk",
                            "image": {
                                "small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
                                "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                                "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                            },
                            "images" : [
                                    {
                                        "small" : "http://api.myretail.cz/images/tomate-250g-14860-1_small.png",
                                        "medium" : "http://api.myretail.cz/images/tomate-250g-14860-1_medium.png",
                                        "large" : "http://api.myretail.cz/images/tomate-250g-14860-1_large.png"
                                    },
                                    {
                                        "small" : "http://api.myretail.cz/images/tomate-250g-14860-2_small.png",
                                        "medium" : "http://api.myretail.cz/images/tomate-250g-14860-2_medium.png",
                                        "large" : "http://api.myretail.cz/images/tomate-250g-14860-2_large.png"
                                    } ]
                        },
                        "priority" : 0.890415,
                        "image": {
                            "small" : "http://img.weiku.com/IMG/2010/11/26/1/product/36_38_tomato_paste17318_s.jpg",
                            "medium" : "http://www.countryliving.com/cm/countryliving/images/spicy-tomato-jam-3761-200.jpg",
                            "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                        },
                        "images" : [ {
                            "small" : "http://api.myretail.cz/images/super_tomate-250g-14860-1_small.png",
                            "medium" : "http://api.myretail.cz/images/super_tomate-250g-14860-1_medium.png",
                            "large" : "http://api.myretail.cz/imagessuper_tomate-250g-14860-1_large.png"
                        } ]
                    }
                },
                {
                    "_id" : {"$oid": "512e6a7bdea8ace96a5854f4"},
                    "type": "discount",
                    "price": -45.21,
                    "currency": 'czk',
                }
            ]
        }
    }
}




Get settings by user id, if has permission
GET /settings
> Content-Type: application/json
{ "user_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Nastavení vrácena", "data": {
    }
}




Get groups by user id, if has permission
GET /groups
> Content-Type: application/json
{ "user_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Skupiny vráceny", "data": {
    }
}




Get notifications by user id, if has permission
GET /notifications
> Content-Type: application/json
{ "user_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Notifikace vráceny", "data": {
    }
}




Get loyality points by user id, if has permission
GET /loyality-points
> Content-Type: application/json
{ "user_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Věrnostní body vráceny", "data": {
    }
}

Get loyality status by user id, if has permission
GET /loyality-status
> Content-Type: application/json
{ "user_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Věrnostní status vrácen", "data": {
    }
}




Get favorite products by user id, if has permission
GET /favorite-products
> Content-Type: application/json
{ "user_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Oblíbené produkty vráceny", "data": {
    }
}



Get discounts by user id, if has permission
GET /discounts
> Content-Type: application/json
{ "user_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Slevy vráceny", "data": {
    }
}



Get branches for retailer id, if has permission
GET /branches
> Content-Type: application/json
{ "retailer_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Oblíbené produkty vráceny", "data": {
    }
}



Get recipes by user id, if has permission
GET /recipes
> Content-Type: application/json
{ "user_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Recepty vráceny", "data": {
    }
}




Get serial offers by user id, if has permission
GET /serial-offers
> Content-Type: application/json
{ "user_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "returned", "message": "Seriálové nabídky vráceny", "data": {
    }
}











--
Modifying Data
The following is a section of resources related to modifying data on server
--


Create new shopping-list for user id, if has permission
GET /create-shopping-list
> Content-Type: application/json
{ "user_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "created", "message": "Nákupní seznam vytvořen", "data": {
    }
}




Rate offer, if has permission
GET /rate-offer
> Content-Type: application/json
{ "offer_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "rated", "message": "Produkt ohodnocen", "data": {
    }
}




Haggle about offer, if has permission
GET /haggle-offer
> Content-Type: application/json
{ "offer_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "haggled", "message": "Nabídka vysmlouvána", "data": {
    }
}




Unwant offer, if has permission
GET /unwanted-offer
> Content-Type: application/json
{ "offer_oid": "512e6a8bdea8ace96a5855f4"}
< 200
< Content-Type: application/json
{ "status": "set-as-unwanted", "message": "Objednávka nastavena jako nechtěná", "data": {
    }
}


